list(APPEND ARG_DEFINES
    LND_HTTP_MP4=$<BOOL:${LND_MODULE_HTTP_MP4}> LND_HTTP_ICY=$<BOOL:${LND_HTTP_ICY}>
    LND_HTTP_HLS=$<BOOL:${LND_MODULE_HTTP_HLS}> LND_HTTP_LL_HLS=$<BOOL:${LND_HTTP_LL_HLS}> LND_HTTP_AES128=$<BOOL:${LND_HTTP_AES128}>)
