file(READ "${source}" code)
set(begin "static OggOpusFile *op_open_close_on_failure(")
set(end "int op_test_open(")
foreach(marker "${begin}" "${end}")
    string(FIND "${code}" "${marker}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Opusfile stream adapter does not match ${source}")
    endif()
endforeach()
string(REPLACE "${begin}" "#if !defined(OP_DISABLE_STREAMS)\n${begin}" code "${code}")
string(REPLACE "${end}" "#endif\n\n${end}" code "${code}")
set(source "${CMAKE_CURRENT_BINARY_DIR}/vendor/opusfile/opusfile.c")
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/vendor/opusfile")
file(WRITE "${source}.tmp" "${code}")
configure_file("${source}.tmp" "${source}" COPYONLY)
file(REMOVE "${source}.tmp")
