if(LND_FFMPEG_BUNDLED)
    lnd_vendor_ffmpeg()
else()
    find_path(LND_FFMPEG_INCLUDE_DIR libavcodec/avcodec.h REQUIRED)
    add_library(lnd_ffmpeg INTERFACE)
    target_include_directories(lnd_ffmpeg INTERFACE ${LND_FFMPEG_INCLUDE_DIR})
    foreach(component avformat avcodec swresample avutil)
        find_library(LND_FFMPEG_${component}_LIBRARY NAMES ${component} REQUIRED)
        target_link_libraries(lnd_ffmpeg INTERFACE ${LND_FFMPEG_${component}_LIBRARY})
    endforeach()
endif()
