#pragma once

#include "lindar_graph.h"

#ifndef LND_DEFAULT_SAMPLE_RATE_HZ
#define LND_DEFAULT_SAMPLE_RATE_HZ 0
#endif

#ifndef LND_DEFAULT_CHANNELS
#define LND_DEFAULT_CHANNELS 0
#endif

#ifndef LND_DEFAULT_BUFFER_FRAMES
#define LND_DEFAULT_BUFFER_FRAMES 4096
#endif

#ifndef LND_DEFAULT_BUFFER_COUNT
#define LND_DEFAULT_BUFFER_COUNT 3
#endif

#ifndef LND_DEFAULT_MIX_BLOCK_FRAMES
#define LND_DEFAULT_MIX_BLOCK_FRAMES 256
#endif

#ifndef LND_DEFAULT_COMMAND_QUEUE_CAPACITY
#define LND_DEFAULT_COMMAND_QUEUE_CAPACITY 1024
#endif

#ifndef LND_DEFAULT_GAIN_RAMP_FRAMES
#define LND_DEFAULT_GAIN_RAMP_FRAMES 128
#endif

#ifndef LND_DEFAULT_CLIP_MODE
#define LND_DEFAULT_CLIP_MODE LND_CLIP_HARD
#endif

#ifndef LND_DEFAULT_MIXER_BUFFER_FRAMES
#define LND_DEFAULT_MIXER_BUFFER_FRAMES 16384
#endif

#ifndef LND_DEFAULT_DRAIN_TIMEOUT_MS
#define LND_DEFAULT_DRAIN_TIMEOUT_MS 200
#endif

#ifndef LND_DEFAULT_POSITION_COMPENSATE
#define LND_DEFAULT_POSITION_COMPENSATE 0
#endif
