cmake_minimum_required(VERSION 3.21)

file(MAKE_DIRECTORY "${LND_TEST_DIR}/source")
file(WRITE "${LND_TEST_DIR}/source/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.21)
project(lindar_package_test NONE)
include("${LND_SOURCE_DIR}/cmake/packages.cmake")
option(LND_MINIMAL "" OFF)
option(LND_OS_MODE "" ON)
option(LND_THREADS "" ON)
option(LND_USE_LIBC_ALLOC "" ON)
option(LND_BUILD_DECODERS "" ON)
option(LND_BUILD_ENCODERS "" ON)
option(LND_SHARED "" OFF)
set(LND_MODULE_DEFAULT ON)
if(LND_MINIMAL)
    set(LND_MODULE_DEFAULT OFF)
endif()
foreach(platform WINDOWS APPLE IOS LINUX ANDROID)
    set(LND_PLATFORM_${platform} OFF)
endforeach()
set(LND_PLATFORM_${TEST_PLATFORM} ON)
if(LND_PLATFORM_IOS)
    set(LND_PLATFORM_APPLE ON)
endif()
set(LND_ANDROID_API ${TEST_API})
set(LND_HTTP_TRANSPORT CURL CACHE STRING "")
include("${LND_SOURCE_DIR}/cmake/modules.cmake")
file(GLOB_RECURSE manifests "${LND_SOURCE_DIR}/modules/*/module.cmake")
list(SORT manifests)
foreach(manifest ${manifests})
    include(${manifest})
endforeach()
lnd_add_module(future DEFAULT ON)
lnd_apply_package()
lnd_resolve_modules()
foreach(name ${EXPECT_ON})
    if(NOT LND_MODULE_${name})
        message(FATAL_ERROR "${LND_PACKAGE}: missing ${name}")
    endif()
endforeach()
foreach(name ${EXPECT_OFF})
    if(LND_MODULE_${name})
        message(FATAL_ERROR "${LND_PACKAGE}: unexpected ${name}")
    endif()
endforeach()
if(LND_PACKAGE STREQUAL "custom")
    set(expected_target lindar)
else()
    set(expected_target ${LND_PACKAGE})
    if(LND_MODULE_FUTURE)
        message(FATAL_ERROR "Fixed package enabled a new default module")
    endif()
    if(LND_PACKAGE STREQUAL "linda")
        if(LND_OS_MODE OR LND_THREADS OR NOT LND_MINIMAL)
            message(FATAL_ERROR "Small package requires OS or threads")
        endif()
    elseif(NOT LND_OS_MODE OR NOT LND_THREADS)
        message(FATAL_ERROR "OS package has inconsistent capabilities")
    endif()
    if(LND_PACKAGE STREQUAL "linda")
        if(LND_USE_LIBC_ALLOC)
            message(FATAL_ERROR "Core package requires libc allocation")
        endif()
        foreach(name ${LND_MODULE_KNOWN})
            string(TOUPPER ${name} upper)
            if(LND_MODULE_${upper})
                message(FATAL_ERROR "Core package contains ${name}")
            endif()
        endforeach()
    elseif(NOT LND_USE_LIBC_ALLOC OR NOT LND_MODULE_WAV_DECODER OR NOT LND_MODULE_WAV_ENCODER)
        message(FATAL_ERROR "Audio package lost allocation or WAV support")
    endif()
endif()
if(NOT LND_LIBRARY_TARGET STREQUAL expected_target)
    message(FATAL_ERROR "Unexpected target ${LND_LIBRARY_TARGET}")
endif()
if(DEFINED EXPECT_SHARED AND NOT LND_SHARED STREQUAL EXPECT_SHARED)
    message(FATAL_ERROR "Package changed the library linkage")
endif()
if(DEFINED EXPECT_FFMPEG_BUNDLED AND NOT LND_FFMPEG_BUNDLED STREQUAL EXPECT_FFMPEG_BUNDLED)
    message(FATAL_ERROR "Package changed FFmpeg linkage")
endif()
if(LND_PACKAGE STREQUAL "lindar" OR LND_PACKAGE STREQUAL "lindar_quanta")
    if(NOT LND_HTTP_TRANSPORT STREQUAL "CURL" OR NOT LND_HTTP_ICY OR NOT LND_HTTP_LL_HLS OR NOT LND_HTTP_AES128)
        message(FATAL_ERROR "OS package lost HTTP features")
    endif()
endif()
]=])

function(check name package platform api enabled disabled)
    set(generator "")
    if(LND_TEST_GENERATOR)
        set(generator -G "${LND_TEST_GENERATOR}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" ${generator}
        -S "${LND_TEST_DIR}/source" -B "${LND_TEST_DIR}/${name}"
        "-DLND_SOURCE_DIR=${LND_SOURCE_DIR}" "-DLND_PACKAGE=${package}"
        "-DTEST_PLATFORM=${platform}" "-DTEST_API=${api}" -DLND_GSTREAMER_AVAILABLE=ON
        "-DEXPECT_ON=${enabled}" "-DEXPECT_OFF=${disabled}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${LND_TEST_DIR}/${name}-${package}-${platform}-${api}.log" "${output}${error}")
    if(DEFINED EXPECT_ERROR)
        if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${EXPECT_ERROR}")
            message(FATAL_ERROR "Expected ${EXPECT_ERROR}: ${output}${error}")
        endif()
    elseif(NOT result EQUAL 0)
        message(FATAL_ERROR "${name}: ${output}${error}")
    endif()
endfunction()

set(basic ADPCM BUFFERS CODECS GRAPH IO OUTPUT PCM_FLOAT QUEUE WAV AUDIO RIFF)
set(os FILE_IO FILES DEVICES STREAM SINK NULL)
set(standard MP3 FLAC OPUS METADATA DSP ANALYSIS NOTIFY
    HTTP HTTP_CURL HTTP_HLS HTTP_MP4 HTTP_FILE DECODE DEMUX CAST MONITOR STRETCH SOUNDTOUCH SINC_ASM)
set(full FFMPEG FFMPEG_STREAM MIDI VST3 EFFECTS BUNGEE)
check(switch lindar_quanta WINDOWS 0 "${basic};${os};${standard};${full};ASIO;WASAPI" ALSA
    -ULND_FFMPEG_BUNDLED -DEXPECT_FFMPEG_BUNDLED=ON
    -DLND_SHARED=ON -DEXPECT_SHARED=ON -DLND_MODULE_WAV_DECODER=OFF -DLND_MODULE_WAV_ENCODER=OFF
    -DLND_MODULE_HTTP=OFF -DLND_HTTP_TRANSPORT=CUSTOM -DLND_HTTP_ICY=OFF -DLND_HTTP_LL_HLS=OFF -DLND_HTTP_AES128=OFF)
check(switch linda WINDOWS 0 "" "${basic};${os};${standard};${full}" -DEXPECT_SHARED=ON)
check(switch lindar_pitya WINDOWS 0 "${basic};${os};WASAPI" "${standard};${full}" -DEXPECT_SHARED=ON)
check(switch lindar WINDOWS 0 "${basic};${os};${standard};WASAPI;MEDIAFOUNDATION" "${full};ASIO;ALSA" -DEXPECT_SHARED=ON)
check(switch lindar_quanta WINDOWS 0 "${basic};${os};${standard};${full};ASIO" "" -DEXPECT_SHARED=ON
    -DLND_FFMPEG_BUNDLED=OFF -DEXPECT_FFMPEG_BUNDLED=OFF)
foreach(package lindar_pitya lindar lindar_quanta)
    set(linux_codecs "")
    set(apple_codecs "")
    set(android_codecs "")
    if(NOT package STREQUAL "lindar_pitya")
        set(linux_codecs ${standard} GSTREAMER)
        set(apple_codecs ${standard} AUDIOTOOLBOX)
        set(android_codecs ${standard} MEDIACODEC)
    endif()
    check(${package}-linux ${package} LINUX 0 "${basic};${os};ALSA;${linux_codecs}" "WASAPI;ASIO;COREAUDIO;AAUDIO")
    check(${package}-apple ${package} APPLE 0 "${basic};${os};COREAUDIO;${apple_codecs}" "WASAPI;ASIO;ALSA;AAUDIO;IOS;ANDROID")
    check(${package}-ios ${package} IOS 0 "${basic};${os};COREAUDIO;IOS;${apple_codecs}" "WASAPI;ASIO;ALSA;AAUDIO;ANDROID")
    check(${package}-android ${package} ANDROID 28 "${basic};${os};AAUDIO;ANDROID;${android_codecs}" "WASAPI;ASIO;ALSA;COREAUDIO")
endforeach()
check(android-21 lindar ANDROID 21 "${basic};NULL" "AAUDIO;ANDROID;IOS;MEDIACODEC")
check(android-26 lindar ANDROID 26 "${basic};NULL;AAUDIO;ANDROID" "MEDIACODEC;IOS")
check(custom custom WINDOWS 0 "QUEUE;FUTURE" "GRAPH;WAV;HTTP" -DLND_MINIMAL=ON
    -DLND_OS_MODE=OFF -DLND_THREADS=OFF -DLND_MODULE_QUEUE=ON -DLND_SHARED=OFF -DEXPECT_SHARED=OFF)
set(EXPECT_ERROR "Unknown LND_PACKAGE")
check(unknown unknown WINDOWS 0 "" "")
set(EXPECT_ERROR "Module gstreamer cannot build")
check(missing lindar LINUX 0 "" "" -DLND_GSTREAMER_AVAILABLE=OFF)
message(STATUS "Package composition, platform selection, cache transitions and custom options passed")
