if(CMAKE_C_COMPILER_ID MATCHES "Clang|GNU" AND NOT CMAKE_C_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
    include(CheckCSourceCompiles)
    set(lnd_try_type "${CMAKE_TRY_COMPILE_TARGET_TYPE}")
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    check_c_source_compiles("#if !defined(__x86_64__) && !defined(_M_X64)\n#error unsupported\n#endif\nint main(void) { return 0; }" LND_TARGET_X64)
    check_c_source_compiles("#if (!defined(__aarch64__) && !defined(_M_ARM64)) || defined(__AARCH64EB__)\n#error unsupported\n#endif\nint main(void) { return 0; }" LND_TARGET_ARM64)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE "${lnd_try_type}")
    if(CMAKE_C_COMPILER_TARGET)
        set(CMAKE_ASM_COMPILER_TARGET "${CMAKE_C_COMPILER_TARGET}")
    endif()
    if(LND_TARGET_X64)
        list(APPEND ARG_SOURCES x64.S)
        list(APPEND ARG_DEFINES LND_SINC_ASM_X64=1)
    elseif(LND_TARGET_ARM64)
        list(APPEND ARG_SOURCES arm64.S)
        list(APPEND ARG_DEFINES LND_SINC_ASM_ARM64=1)
    endif()
endif()
