set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_FLAGS_INIT "-ffunction-sections -fdata-sections")
if(LND_QEMU_BOARD STREQUAL "avr")
    set(CMAKE_SYSTEM_PROCESSOR avr)
    set(CMAKE_C_COMPILER avr-gcc)
    string(APPEND CMAKE_C_FLAGS_INIT " -mmcu=atmega2560")
else()
    set(CMAKE_SYSTEM_PROCESSOR arm)
    set(CMAKE_C_COMPILER arm-none-eabi-gcc)
    if(LND_QEMU_BOARD STREQUAL "m0")
        set(cpu cortex-m0)
    elseif(LND_QEMU_BOARD STREQUAL "m33")
        set(cpu cortex-m33)
    else()
        message(FATAL_ERROR "Unknown Cortex board: ${LND_QEMU_BOARD}")
    endif()
    string(APPEND CMAKE_C_FLAGS_INIT " -mcpu=${cpu} -mthumb -mfloat-abi=soft")
endif()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES LND_QEMU_BOARD)
