if(CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
    foreach(source x86.c x86_sse2.c x86_avx.c x86_avx2.c x86_avx512.c neon.c sinc_neon.c sinc_sse2.c sinc_avx.c sinc_avx512.c)
        set_source_files_properties(${CMAKE_CURRENT_LIST_DIR}/${source} PROPERTIES COMPILE_OPTIONS "-ffp-contract=off")
    endforeach()
endif()
if(MSVC AND NOT CMAKE_C_COMPILER_ID MATCHES "Clang")
    include(CheckCSourceCompiles)
    set(lnd_try_type "${CMAKE_TRY_COMPILE_TARGET_TYPE}")
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    check_c_source_compiles("#if !defined(_M_X64) && !defined(_M_IX86)\n#error unsupported\n#endif\nint main(void) { return 0; }" LND_MSVC_X86)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE "${lnd_try_type}")
    foreach(source x86.c x86_sse2.c x86_avx.c x86_avx2.c x86_avx512.c neon.c sinc_neon.c sinc_sse2.c sinc_avx.c sinc_avx512.c)
        set_source_files_properties(${CMAKE_CURRENT_LIST_DIR}/${source} PROPERTIES COMPILE_OPTIONS "/fp:strict")
    endforeach()
    if(LND_MSVC_X86)
        foreach(level avx avx2 avx512)
            string(TOUPPER ${level} arch)
            set_property(SOURCE ${CMAKE_CURRENT_LIST_DIR}/x86_${level}.c APPEND PROPERTY COMPILE_OPTIONS "/arch:${arch}")
        endforeach()
        foreach(level avx avx512)
            string(TOUPPER ${level} arch)
            set_property(SOURCE ${CMAKE_CURRENT_LIST_DIR}/sinc_${level}.c APPEND PROPERTY COMPILE_OPTIONS "/arch:${arch}")
        endforeach()
    endif()
endif()
