lnd_vendor_soundtouch()
add_library(lnd_soundtouch_bridge STATIC ${CMAKE_CURRENT_LIST_DIR}/bridge.cpp)
target_include_directories(lnd_soundtouch_bridge PRIVATE ${LND_VENDOR_DIR}/soundtouch/include ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_compile_definitions(lnd_soundtouch_bridge PRIVATE SOUNDTOUCH_FLOAT_SAMPLES=1)
target_link_libraries(lnd_soundtouch_bridge PUBLIC lnd_soundtouch)
set_target_properties(lnd_soundtouch_bridge PROPERTIES CXX_STANDARD 17 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF POSITION_INDEPENDENT_CODE ON CXX_VISIBILITY_PRESET hidden)
if(MSVC)
    target_compile_options(lnd_soundtouch_bridge PRIVATE /EHsc)
else()
    target_compile_options(lnd_soundtouch_bridge PRIVATE -fexceptions -Wall -Wextra)
endif()
