lnd_vendor_bungee()
add_library(lnd_bungee_bridge STATIC ${CMAKE_CURRENT_LIST_DIR}/bridge.cpp)
target_include_directories(lnd_bungee_bridge PRIVATE ${LND_VENDOR_DIR}/bungee ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(lnd_bungee_bridge PUBLIC lnd_bungee)
set_target_properties(lnd_bungee_bridge PROPERTIES CXX_STANDARD 20 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF POSITION_INDEPENDENT_CODE ON CXX_VISIBILITY_PRESET hidden)
if(MSVC)
    target_compile_options(lnd_bungee_bridge PRIVATE /EHsc)
else()
    target_compile_options(lnd_bungee_bridge PRIVATE -fexceptions -Wall -Wextra)
endif()
