file(COPY ${LND_VENDOR_DIR}/vst3_pluginterfaces/ DESTINATION ${LND_GENERATED_DIR}/vst3/pluginterfaces PATTERN ".git" EXCLUDE)
add_library(lnd_vst3_bridge STATIC ${CMAKE_CURRENT_LIST_DIR}/host.cpp ${CMAKE_CURRENT_LIST_DIR}/module.cpp
    ${CMAKE_CURRENT_LIST_DIR}/preset.cpp ${CMAKE_CURRENT_LIST_DIR}/iids.cpp ${LND_GENERATED_DIR}/vst3/pluginterfaces/base/funknown.cpp)
target_include_directories(lnd_vst3_bridge SYSTEM PRIVATE ${LND_GENERATED_DIR}/vst3)
target_include_directories(lnd_vst3_bridge PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include ${CMAKE_CURRENT_SOURCE_DIR} ${LND_GENERATED_DIR})
set_target_properties(lnd_vst3_bridge PROPERTIES CXX_STANDARD 17 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF POSITION_INDEPENDENT_CODE ON CXX_VISIBILITY_PRESET hidden)
if(MSVC)
    target_compile_options(lnd_vst3_bridge PRIVATE /EHsc)
else()
    target_compile_options(lnd_vst3_bridge PRIVATE -fexceptions -Wall -Wextra -Wno-unused-parameter)
endif()
if(APPLE)
    target_link_libraries(lnd_vst3_bridge PRIVATE "-framework CoreFoundation")
elseif(UNIX)
    target_link_libraries(lnd_vst3_bridge PRIVATE ${CMAKE_DL_LIBS})
endif()
