cmake_minimum_required(VERSION 3.21)
get_filename_component(LND_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
include("${LND_ROOT}/cmake/packages.cmake")
set(LND_MODULE_DEFAULT ON)
if(LND_MINIMAL)
    set(LND_MODULE_DEFAULT OFF)
endif()
set(LND_HTTP_TRANSPORT CURL CACHE STRING "")
set(LND_GSTREAMER_AVAILABLE ON)
foreach(platform WINDOWS LINUX APPLE IOS ANDROID)
    set(LND_PLATFORM_${platform} OFF)
endforeach()
set(LND_PLATFORM_${LND_DOCS_PLATFORM} ON)
if(LND_PLATFORM_IOS)
    set(LND_PLATFORM_APPLE ON)
endif()
set(LND_ANDROID_API 28)
include("${LND_ROOT}/cmake/modules.cmake")
file(GLOB_RECURSE manifests "${LND_ROOT}/modules/*/module.cmake")
list(SORT manifests)
foreach(manifest IN LISTS manifests)
    include("${manifest}")
endforeach()
lnd_apply_package()
lnd_resolve_modules()

function(lnd_docs_quote result value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${result} "\"${value}\"" PARENT_SCOPE)
endfunction()

set(document "{}")
foreach(name IN LISTS LND_MODULE_KNOWN)
    set(module "{}")
    get_property(directory GLOBAL PROPERTY LND_DECL_${name}_DIR)
    file(RELATIVE_PATH directory "${LND_ROOT}" "${directory}")
    lnd_docs_quote(quoted "${directory}")
    string(JSON module SET "${module}" directory "${quoted}")
    foreach(field HEADER INTERNAL DECODER ENCODER PLATFORM MIN_API AVAILABLE PROVIDES PROVIDER_KIND
            REQUIRES_PROVIDER REQUIRES REQUIRES_ONE_OF REQUIRES_IF DECODER_REQUIRES ENCODER_REQUIRES
            DEFAULT_WITH LANGUAGES LIBS)
        get_property(value GLOBAL PROPERTY LND_DECL_${name}_${field})
        set(values "[]")
        set(index 0)
        foreach(item IN LISTS value)
            lnd_docs_quote(quoted "${item}")
            string(JSON values SET "${values}" ${index} "${quoted}")
            math(EXPR index "${index} + 1")
        endforeach()
        string(TOLOWER "${field}" key)
        string(JSON module SET "${module}" "${key}" "${values}")
    endforeach()
    get_property(enabled GLOBAL PROPERTY LND_RESOLVED_${name})
    if(enabled)
        string(JSON module SET "${module}" enabled true)
    else()
        string(JSON module SET "${module}" enabled false)
    endif()
    string(JSON document SET "${document}" "${name}" "${module}")
endforeach()
file(WRITE "${LND_DOCS_METADATA}" "${document}\n")
