function(lnd_example category name)
    if(category MATCHES "^os" AND (NOT LND_OS_MODE OR NOT LND_USE_LIBC_ALLOC))
        return()
    endif()
    foreach(requirement IN LISTS ARGN)
        if(NOT ${requirement})
            return()
        endif()
    endforeach()
    add_executable(${name} examples/${category}/${name}/main.c)
    set_target_properties(${name} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/examples")
    target_link_libraries(${name} PRIVATE lindar)
    if(UNIX)
        target_link_libraries(${name} PRIVATE m)
    endif()
    if(CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
        target_compile_options(${name} PRIVATE -Wall -Wextra)
    endif()
    set_property(GLOBAL APPEND PROPERTY LND_EXAMPLE_TARGETS ${name})
endfunction()

lnd_example(mcu manual)
lnd_example(mcu sine_mcu)
target_sources(sine_mcu PRIVATE examples/mcu/sine_mcu/sine_mcu.c)
lnd_example(mcu pcm_convert)
lnd_example(mcu pcm_layout)
lnd_example(mcu source_memory)
lnd_example(mcu source_callback)
lnd_example(mcu transport)
lnd_example(mcu stream_mcu LND_MODULE_QUEUE)
lnd_example(mcu http_mcu LND_MODULE_HTTP LND_MODULE_WAV_DECODER LND_USE_LIBC_ALLOC)
lnd_example(mcu adpcm_mcu LND_MODULE_ADPCM_DECODER)
lnd_example(mcu opus_mcu LND_MODULE_OPUS_DECODER)
foreach(name adpcm_mcu opus_mcu)
    if(TARGET ${name})
        target_sources(${name} PRIVATE examples/mcu/file_mcu/file_mcu.c)
        target_include_directories(${name} PRIVATE examples/mcu/file_mcu)
    endif()
endforeach()

lnd_example(os manual_graph LND_MODULE_GRAPH LND_MODULE_PCM_FLOAT)
lnd_example(os planar LND_MODULE_GRAPH LND_MODULE_PCM_FLOAT)
lnd_example(os graph_mixer LND_MODULE_GRAPH)
lnd_example(os graph_splitter LND_MODULE_GRAPH)
lnd_example(os graph_channels LND_MODULE_GRAPH)
lnd_example(os notifications LND_MODULE_NOTIFY)
if(NOT LND_MODULE_DEVICES OR LND_MODULE_NULL)
    lnd_example(os notifications_realtime LND_MODULE_NOTIFY LND_THREADS)
endif()
lnd_example(os slide_autofree LND_MODULE_SLIDE LND_MODULE_AUTOFREE LND_MODULE_PCM_FLOAT)
lnd_example(os varispeed LND_MODULE_DSP)
lnd_example(os effects LND_MODULE_EFFECTS)
lnd_example(os stretch LND_MODULE_STRETCH)
lnd_example(os soundtouch LND_MODULE_SOUNDTOUCH)
lnd_example(os analysis_levels LND_MODULE_ANALYSIS)
lnd_example(os analysis_fft LND_MODULE_ANALYSIS)
lnd_example(os metadata LND_MODULE_METADATA_IO LND_MODULE_FILE_IO)
lnd_example(os metadata_edit LND_MODULE_METADATA_ID3V2)
lnd_example(os convert LND_MODULE_FILES LND_MODULE_OUTPUT LND_DECODER_NAMES LND_ENCODER_NAMES)
lnd_example(os render_file LND_MODULE_FILES LND_MODULE_OUTPUT LND_MODULE_WAV_ENCODER)
lnd_example(os output_callback LND_MODULE_OUTPUT LND_MODULE_WAV_ENCODER)
lnd_example(os decode_push LND_MODULE_DECODE LND_MODULE_WAV_DECODER)
lnd_example(os midi_synth LND_MODULE_MIDI LND_MODULE_FILE_IO)
lnd_example(os vst3_host LND_MODULE_VST3)
lnd_example(os monitor LND_MODULE_MONITOR)
lnd_example(os devices LND_MODULE_DEVICES)
lnd_example(os device_events LND_MODULE_DEVICES LND_THREADS)
lnd_example(os device_tone LND_MODULE_DEVICES LND_THREADS)
lnd_example(os file_play LND_MODULE_DEVICES LND_MODULE_FILES LND_THREADS LND_DECODER_NAMES)
lnd_example(os record LND_MODULE_DEVICES LND_MODULE_FILES LND_MODULE_OUTPUT LND_MODULE_WAV_ENCODER LND_THREADS)
if(LND_HTTP_TRANSPORT STREQUAL "CURL")
    lnd_example(os httpplay LND_MODULE_HTTP LND_MODULE_DEVICES LND_THREADS)
endif()
if(WIN32)
    lnd_example(os-windows asio_duplex LND_MODULE_ASIO)
endif()

get_property(examples GLOBAL PROPERTY LND_EXAMPLE_TARGETS)
if(WIN32 AND LND_SHARED)
    set(runtime "${CMAKE_CURRENT_BINARY_DIR}/examples")
    if(CMAKE_CONFIGURATION_TYPES)
        string(APPEND runtime "/$<CONFIG>")
    endif()
    add_custom_target(lindar_example_runtime ALL
        COMMAND ${CMAKE_COMMAND} -E make_directory "${runtime}"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:lindar> "${runtime}"
        DEPENDS lindar
        VERBATIM)
    foreach(name IN LISTS examples)
        add_dependencies(${name} lindar_example_runtime)
    endforeach()
endif()
set(example_paths "")
foreach(name IN LISTS examples)
    string(APPEND example_paths "$<TARGET_FILE:${name}>\n")
endforeach()
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/examples-$<CONFIG>.txt" CONTENT "${example_paths}")
