if(LND_MODULE_VST3)
    add_library(lindar_vst3_fixture MODULE tests/vst3_plugin.cpp ${LND_GENERATED_DIR}/vst3/pluginterfaces/base/funknown.cpp)
    target_include_directories(lindar_vst3_fixture SYSTEM PRIVATE ${LND_GENERATED_DIR}/vst3)
    target_compile_features(lindar_vst3_fixture PRIVATE cxx_std_17)
    set_target_properties(lindar_vst3_fixture PROPERTIES PREFIX "")
    if(APPLE)
        set_target_properties(lindar_vst3_fixture PROPERTIES BUNDLE TRUE BUNDLE_EXTENSION vst3)
        target_link_libraries(lindar_vst3_fixture PRIVATE "-framework CoreFoundation")
        set(vst3_fixture_path $<TARGET_BUNDLE_DIR:lindar_vst3_fixture>)
    else()
        set_target_properties(lindar_vst3_fixture PROPERTIES SUFFIX ".vst3")
        set(vst3_fixture_path $<TARGET_FILE:lindar_vst3_fixture>)
        if(WIN32)
            target_link_libraries(lindar_vst3_fixture PRIVATE ole32)
        endif()
    endif()
    add_executable(lindar_vst3_tests tests/test_vst3.c)
    target_link_libraries(lindar_vst3_tests PRIVATE lindar)
    add_dependencies(lindar_vst3_tests lindar_vst3_fixture)
    add_test(NAME lindar_vst3_tests COMMAND lindar_vst3_tests ${vst3_fixture_path})
    set_tests_properties(lindar_vst3_tests PROPERTIES TIMEOUT 20)
endif()
if(LND_MODULE_MIDI)
    add_executable(lindar_midi_tests tests/test_midi.c)
    target_link_libraries(lindar_midi_tests PRIVATE lindar)
    add_test(NAME lindar_midi_tests COMMAND lindar_midi_tests ${CMAKE_CURRENT_SOURCE_DIR}/vendor/tinysoundfont/examples/florestan-subset.sf2)
    set_tests_properties(lindar_midi_tests PROPERTIES TIMEOUT 20)
endif()
if(LND_MODULE_DECODE AND LND_THREADS)
    add_executable(lindar_audio_extensions_tests tests/test_audio_extensions.c)
    target_include_directories(lindar_audio_extensions_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/modules)
    target_link_libraries(lindar_audio_extensions_tests PRIVATE ${LND_INTERNAL_TEST_LIBRARY})
    add_test(NAME lindar_audio_extensions_tests COMMAND lindar_audio_extensions_tests)
    set_tests_properties(lindar_audio_extensions_tests PROPERTIES TIMEOUT 35)
endif()
if(LND_MODULE_CAST)
    find_program(LND_RUBY_EXECUTABLE ruby REQUIRED)
    add_executable(lindar_cast_tests tests/test_cast.c)
    target_include_directories(lindar_cast_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/modules)
    target_link_libraries(lindar_cast_tests PRIVATE ${LND_INTERNAL_TEST_LIBRARY})
    add_test(NAME lindar_cast_tests COMMAND ${LND_RUBY_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/cast_server.rb $<TARGET_FILE:lindar_cast_tests>)
    set_tests_properties(lindar_cast_tests PROPERTIES TIMEOUT 25)
endif()
if(LND_MODULE_SPEEX_DECODER)
    add_executable(lindar_speex_tests tests/test_speex.c)
    target_link_libraries(lindar_speex_tests PRIVATE lindar)
    add_test(NAME lindar_speex_tests COMMAND lindar_speex_tests)
    set_tests_properties(lindar_speex_tests PROPERTIES TIMEOUT 15)
endif()
