include(GNUInstallDirs)
set(LND_PUBLIC_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/include/lindar.h" ${LND_MODULE_HEADERS})
set(pending ${LND_PUBLIC_HEADERS})
while(pending)
    list(POP_FRONT pending header)
    file(STRINGS "${header}" includes REGEX "^#include \"[^\"]+\"")
    foreach(line ${includes})
        string(REGEX REPLACE "^#include \"([^\"]+)\".*" "\\1" name "${line}")
        set(dependency "${CMAKE_CURRENT_SOURCE_DIR}/include/${name}")
        if(NOT EXISTS "${dependency}")
            message(FATAL_ERROR "Missing public header ${name}, included by ${header}")
        endif()
        if(NOT dependency IN_LIST LND_PUBLIC_HEADERS)
            list(APPEND LND_PUBLIC_HEADERS "${dependency}")
            list(APPEND pending "${dependency}")
        endif()
    endforeach()
endwhile()
list(REMOVE_DUPLICATES LND_PUBLIC_HEADERS)
list(SORT LND_PUBLIC_HEADERS)
list(APPEND LND_PUBLIC_HEADERS "${LND_GENERATED_DIR}/lnd_modules.h")
install(TARGETS ${LND_LIBRARY_TARGET} RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Lindar
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Lindar
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT Lindar)
install(FILES ${LND_PUBLIC_HEADERS} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR} COMPONENT Lindar)
install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE" DESTINATION ${CMAKE_INSTALL_DATADIR}/licenses/lindar COMPONENT Lindar)
file(GENERATE OUTPUT "${LND_GENERATED_DIR}/public-headers.txt" CONTENT "$<JOIN:${LND_PUBLIC_HEADERS},\n>\n")
