set(LND_MODULE_NAMES "")
set(LND_MODULE_KNOWN "")
set(LND_MODULE_SOURCES "")
set(LND_MODULE_LIBS "")
set(LND_MODULE_DEFINES "")
set(LND_MODULE_HEADERS "")
set(LND_MODULE_REQUIREMENTS "")
set(LND_DECODER_NAMES "")
set(LND_DECODER_KNOWN "")
set(LND_ENCODER_NAMES "")
set(LND_ENCODER_KNOWN "")

function(lnd_import_option OLD NEW)
    if(DEFINED CACHE{${OLD}})
        if(NOT DEFINED CACHE{${NEW}} OR "$CACHE{${NEW}}" STREQUAL "AUTO")
            set(${NEW} "$CACHE{${OLD}}" CACHE STRING "Module selection: AUTO, ON or OFF" FORCE)
        elseif(NOT "$CACHE{${OLD}}" STREQUAL "$CACHE{${NEW}}")
            message(STATUS "${OLD} is obsolete; ${NEW} takes precedence")
        endif()
        message(STATUS "Migrating ${OLD} to ${NEW}")
        unset(${OLD} CACHE)
    endif()
endfunction()

function(lnd_module_mode OPTION)
    if(NOT DEFINED CACHE{${OPTION}})
        set(${OPTION} AUTO CACHE STRING "Module selection: AUTO, ON or OFF")
    endif()
    set_property(CACHE ${OPTION} PROPERTY TYPE STRING)
    set_property(CACHE ${OPTION} PROPERTY STRINGS AUTO ON OFF)
    string(TOUPPER "$CACHE{${OPTION}}" mode)
    if(mode MATCHES "^(1|TRUE|YES|Y)$")
        set(mode ON)
    elseif(mode MATCHES "^(0|FALSE|NO|N)$")
        set(mode OFF)
    endif()
    if(NOT mode MATCHES "^(AUTO|ON|OFF)$")
        message(FATAL_ERROR "${OPTION} must be AUTO, ON or OFF")
    endif()
    set(${OPTION}_REQUEST ${mode} PARENT_SCOPE)
endfunction()

function(lnd_add_module NAME)
    cmake_parse_arguments(ARG "DECODER;ENCODER;OS_MODE;THREADS;INTERNAL"
        "DEFAULT;DEFAULT_WITH;HEADER;CONFIG;ERRORS;PROVIDES;PROVIDER_KIND;REQUIRES_PROVIDER;PRIORITY;INIT;START;STOP;FREE;UPDATE;MAINTAIN;CONFIG_SET;SETUP;PLATFORM;MIN_API;AVAILABLE"
        "PROVIDER;LANGUAGES;SOURCES;REQUIRES;LIBS;DEFINES;REQUIRES_ONE_OF;DECODER_REQUIRES;ENCODER_REQUIRES;DECODER_SOURCES;ENCODER_SOURCES;SOURCES_IF;REQUIRES_IF"
        ${ARGN})
    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unknown declaration in module ${NAME}: ${ARG_UNPARSED_ARGUMENTS}")
    endif()
    if(NAME IN_LIST LND_MODULE_KNOWN)
        message(FATAL_ERROR "Duplicate module ${NAME}")
    endif()
    get_property(directories GLOBAL PROPERTY LND_MODULE_DIRECTORIES)
    if(CMAKE_CURRENT_LIST_DIR IN_LIST directories)
        message(FATAL_ERROR "Each directory declares exactly one module: ${CMAKE_CURRENT_LIST_DIR}")
    endif()
    set_property(GLOBAL APPEND PROPERTY LND_MODULE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}")
    if(NOT DEFINED ARG_DEFAULT)
        if(ARG_INTERNAL)
            set(ARG_DEFAULT OFF)
        else()
            set(ARG_DEFAULT ${LND_MODULE_DEFAULT})
        endif()
    endif()
    if(ARG_DEFAULT_WITH)
        set(ARG_DEFAULT OFF)
    endif()
    if(ARG_HEADER AND NOT ARG_HEADER STREQUAL "lindar_${NAME}.h")
        message(FATAL_ERROR "Module ${NAME} must use HEADER lindar_${NAME}.h")
    endif()
    if(ARG_PROVIDES AND NOT ARG_PROVIDER_KIND MATCHES "^(NATIVE|EXTENSION|FALLBACK)$")
        message(FATAL_ERROR "Module ${NAME} must declare PROVIDER_KIND NATIVE, EXTENSION or FALLBACK")
    endif()
    if(ARG_CONFIG AND NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/config.h")
        message(FATAL_ERROR "Module ${NAME} must own config.h for its configuration")
    endif()
    if(NOT DEFINED ARG_PRIORITY)
        set(ARG_PRIORITY 50)
    endif()
    if(ARG_OS_MODE)
        list(APPEND ARG_REQUIRES OS_MODE)
    endif()
    if(ARG_THREADS)
        list(APPEND ARG_REQUIRES THREADS)
    endif()
    string(TOUPPER ${NAME} upper)
    if(ARG_INTERNAL)
        set(LND_MODULE_${upper}_REQUEST AUTO)
    else()
        lnd_module_mode(LND_MODULE_${upper})
    endif()
    set_property(GLOBAL PROPERTY LND_DECL_${NAME}_REQUEST ${LND_MODULE_${upper}_REQUEST})
    foreach(kind DECODER ENCODER)
        if(ARG_${kind})
            lnd_module_mode(LND_MODULE_${upper}_${kind})
            set_property(GLOBAL PROPERTY LND_DECL_${NAME}_${kind}_REQUEST ${LND_MODULE_${upper}_${kind}_REQUEST})
            list(APPEND LND_${kind}_KNOWN ${NAME})
            set(LND_${kind}_KNOWN ${LND_${kind}_KNOWN} PARENT_SCOPE)
        endif()
    endforeach()
    foreach(field INTERNAL DECODER ENCODER DEFAULT DEFAULT_WITH PRIORITY INIT START STOP FREE UPDATE MAINTAIN CONFIG_SET
            SETUP PLATFORM MIN_API AVAILABLE LANGUAGES SOURCES HEADER CONFIG ERRORS PROVIDES PROVIDER_KIND REQUIRES_PROVIDER PROVIDER REQUIRES LIBS DEFINES REQUIRES_ONE_OF DECODER_REQUIRES ENCODER_REQUIRES
            DECODER_SOURCES ENCODER_SOURCES SOURCES_IF REQUIRES_IF)
        set_property(GLOBAL PROPERTY LND_DECL_${NAME}_${field} "${ARG_${field}}")
    endforeach()
    set_property(GLOBAL PROPERTY LND_DECL_${NAME}_DIR "${CMAKE_CURRENT_LIST_DIR}")
    list(APPEND LND_MODULE_KNOWN ${NAME})
    set(LND_MODULE_KNOWN ${LND_MODULE_KNOWN} PARENT_SCOPE)
endfunction()

function(lnd_module_capability NAME RESULT)
    get_property(requirements GLOBAL PROPERTY LND_DECL_${NAME}_REQUIRES)
    set(ok ON)
    foreach(cap OS_MODE THREADS)
        if(cap IN_LIST requirements AND NOT LND_${cap})
            set(ok OFF)
        endif()
    endforeach()
    get_property(platform GLOBAL PROPERTY LND_DECL_${NAME}_PLATFORM)
    if(platform AND NOT LND_PLATFORM_${platform})
        set(ok OFF)
    endif()
    get_property(api GLOBAL PROPERTY LND_DECL_${NAME}_MIN_API)
    if(api AND LND_ANDROID_API LESS api)
        set(ok OFF)
    endif()
    get_property(available GLOBAL PROPERTY LND_DECL_${NAME}_AVAILABLE)
    if(available)
        if(NOT ${available})
            set(ok OFF)
        endif()
    endif()
    set(${RESULT} ${ok} PARENT_SCOPE)
endfunction()

function(lnd_module_providers KIND RESULT)
    set(providers "")
    set(names ${LND_MODULE_KNOWN})
    list(SORT names)
    foreach(role NATIVE EXTENSION FALLBACK)
        foreach(name ${names})
            get_property(kind GLOBAL PROPERTY LND_DECL_${name}_PROVIDES)
            get_property(priority GLOBAL PROPERTY LND_DECL_${name}_PROVIDER_KIND)
            if(kind STREQUAL KIND AND priority STREQUAL role)
                list(APPEND providers ${name})
            endif()
        endforeach()
    endforeach()
    set(${RESULT} ${providers} PARENT_SCOPE)
endfunction()

function(lnd_resolve_modules)
    foreach(name ${LND_MODULE_KNOWN})
        get_property(mode_${name} GLOBAL PROPERTY LND_DECL_${name}_REQUEST)
        get_property(default GLOBAL PROPERTY LND_DECL_${name}_DEFAULT)
        get_property(requires_${name} GLOBAL PROPERTY LND_DECL_${name}_REQUIRES)
        get_property(choices_${name} GLOBAL PROPERTY LND_DECL_${name}_REQUIRES_ONE_OF)
        get_property(provider GLOBAL PROPERTY LND_DECL_${name}_REQUIRES_PROVIDER)
        if(provider)
            lnd_module_providers(${provider} providers)
            if(NOT providers)
                message(FATAL_ERROR "Module ${name} requires a provider of ${provider}")
            endif()
            list(APPEND choices_${name} ${providers})
        endif()
        get_property(conditional_${name} GLOBAL PROPERTY LND_DECL_${name}_REQUIRES_IF)
        foreach(pair ${conditional_${name}})
            string(REPLACE ":" ";" parts "${pair}")
            foreach(req ${parts})
                if(NOT req IN_LIST LND_MODULE_KNOWN)
                    message(FATAL_ERROR "Module ${name} refers to unknown module ${req}")
                endif()
            endforeach()
        endforeach()
        foreach(req ${requires_${name}} ${choices_${name}})
            if(NOT req IN_LIST LND_MODULE_KNOWN AND NOT req MATCHES "^(OS_MODE|THREADS)$")
                message(FATAL_ERROR "Module ${name} requires unknown module ${req}")
            endif()
        endforeach()
        set(has_codec OFF)
        set(codec_active OFF)
        foreach(kind DECODER ENCODER)
            get_property(has GLOBAL PROPERTY LND_DECL_${name}_${kind})
            set(${kind}_${name} OFF)
            if(has)
                set(has_codec ON)
                get_property(mode GLOBAL PROPERTY LND_DECL_${name}_${kind}_REQUEST)
                get_property(kind_requires GLOBAL PROPERTY LND_DECL_${name}_${kind}_REQUIRES)
                if(LND_BUILD_${kind}S AND NOT mode STREQUAL "OFF")
                    set(${kind}_${name} ON)
                    set(codec_active ON)
                    list(APPEND requires_${name} ${kind_requires})
                    if(kind STREQUAL "DECODER")
                        list(APPEND requires_${name} codecs)
                    else()
                        list(APPEND requires_${name} output)
                    endif()
                endif()
            endif()
        endforeach()
        set(enabled_${name} OFF)
        lnd_module_capability(${name} capable)
        if(mode_${name} STREQUAL "ON" OR (mode_${name} STREQUAL "AUTO" AND default AND capable))
            if(NOT has_codec OR codec_active)
                set(enabled_${name} ON)
            endif()
        endif()
        set(dormant_${name} OFF)
        if(has_codec AND NOT codec_active)
            set(dormant_${name} ON)
            if(mode_${name} STREQUAL "ON")
                message(FATAL_ERROR "Module ${name} is ON but all of its decoder/encoder implementations are disabled")
            endif()
        endif()
    endforeach()
    if(NOT LND_HTTP_TRANSPORT STREQUAL "CUSTOM")
        string(TOLOWER "${LND_HTTP_TRANSPORT}" transport)
        set(transport "http_${transport}")
        get_property(kind GLOBAL PROPERTY LND_DECL_${transport}_PROVIDES)
        if(NOT kind STREQUAL "http_transport")
            message(FATAL_ERROR "Unknown HTTP transport ${LND_HTTP_TRANSPORT}")
        endif()
        list(APPEND requires_http ${transport})
    endif()
    set(changed ON)
    while(changed)
        set(changed OFF)
        foreach(name ${LND_MODULE_KNOWN})
            get_property(parent GLOBAL PROPERTY LND_DECL_${name}_DEFAULT_WITH)
            lnd_module_capability(${name} capable)
            if(parent AND enabled_${parent} AND mode_${name} STREQUAL "AUTO" AND capable AND NOT enabled_${name} AND NOT dormant_${name})
                set(enabled_${name} ON)
                set(changed ON)
            endif()
            if(NOT enabled_${name})
                continue()
            endif()
            foreach(pair ${conditional_${name}})
                string(REPLACE ":" ";" parts "${pair}")
                list(GET parts 0 condition)
                list(GET parts 1 dependency)
                if(enabled_${condition})
                    list(APPEND requires_${name} ${dependency})
                endif()
            endforeach()
            list(REMOVE_DUPLICATES requires_${name})
            foreach(req ${requires_${name}})
                if(req STREQUAL "OS_MODE" OR req STREQUAL "THREADS")
                    continue()
                endif()
                if(NOT req IN_LIST LND_MODULE_KNOWN)
                    message(FATAL_ERROR "Module ${name} requires unknown module ${req}")
                endif()
                if(mode_${req} STREQUAL "OFF" OR dormant_${req})
                    string(TOUPPER ${req} upper)
                    message(FATAL_ERROR "Module ${name} requires ${req}, but LND_MODULE_${upper} is disabled; select AUTO/ON or disable ${name}")
                endif()
                if(NOT enabled_${req})
                    set(enabled_${req} ON)
                    set(changed ON)
                endif()
            endforeach()
        endforeach()
        if(changed)
            continue()
        endif()
        foreach(name ${LND_MODULE_KNOWN})
            if(NOT enabled_${name} OR NOT choices_${name})
                continue()
            endif()
            set(selected "")
            foreach(candidate ${choices_${name}})
                if(enabled_${candidate})
                    set(selected ${candidate})
                    break()
                endif()
            endforeach()
            if(NOT selected)
                foreach(candidate ${choices_${name}})
                    lnd_module_capability(${candidate} capable)
                    if(NOT mode_${candidate} STREQUAL "OFF" AND NOT dormant_${candidate} AND capable)
                        set(selected ${candidate})
                        set(enabled_${candidate} ON)
                        set(changed ON)
                        break()
                    endif()
                endforeach()
            endif()
            if(NOT selected)
                message(FATAL_ERROR "Module ${name} requires one of: ${choices_${name}}; all implementations are disabled or unavailable")
            endif()
            list(APPEND requires_${name} ${selected})
            list(REMOVE_DUPLICATES requires_${name})
        endforeach()
    endwhile()
    foreach(name ${LND_MODULE_KNOWN})
        string(TOUPPER ${name} upper)
        set(LND_MODULE_${upper} ${enabled_${name}} PARENT_SCOPE)
        set_property(GLOBAL PROPERTY LND_RESOLVED_${name} ${enabled_${name}})
        if(enabled_${name})
            lnd_module_capability(${name} capable)
            if(NOT capable)
                get_property(platform GLOBAL PROPERTY LND_DECL_${name}_PLATFORM)
                get_property(api GLOBAL PROPERTY LND_DECL_${name}_MIN_API)
                get_property(available GLOBAL PROPERTY LND_DECL_${name}_AVAILABLE)
                message(FATAL_ERROR "Module ${name} cannot build: requires ${requires_${name}}; platform=${platform}; Android API>=${api}; availability=${available}")
            endif()
        endif()
        foreach(kind DECODER ENCODER)
            set(active OFF)
            if(enabled_${name} AND ${kind}_${name})
                set(active ON)
            endif()
            set(LND_MODULE_${upper}_${kind} ${active} PARENT_SCOPE)
        endforeach()
        foreach(req ${requires_${name}})
            list(APPEND LND_MODULE_REQUIREMENTS "${name}:${req}")
        endforeach()
    endforeach()
    set(LND_MODULE_REQUIREMENTS ${LND_MODULE_REQUIREMENTS} PARENT_SCOPE)
endfunction()

function(lnd_materialize_module NAME)
    string(TOUPPER ${NAME} upper)
    if(NOT LND_MODULE_${upper})
        return()
    endif()
    foreach(field PRIORITY INIT START STOP FREE UPDATE MAINTAIN CONFIG_SET SETUP SOURCES HEADER LIBS DEFINES
            DECODER_SOURCES ENCODER_SOURCES SOURCES_IF)
        get_property(ARG_${field} GLOBAL PROPERTY LND_DECL_${NAME}_${field})
    endforeach()
    get_property(dir GLOBAL PROPERTY LND_DECL_${NAME}_DIR)
    foreach(kind DECODER ENCODER)
        set(ARG_${kind} ${LND_MODULE_${upper}_${kind}})
        if(ARG_${kind})
            list(APPEND ARG_SOURCES ${ARG_${kind}_SOURCES})
        endif()
    endforeach()
    foreach(pair ${ARG_SOURCES_IF})
        string(REPLACE ":" ";" parts "${pair}")
        list(GET parts 0 dependency)
        list(GET parts 1 value)
        string(TOUPPER ${dependency} dep_upper)
        if(LND_MODULE_${dep_upper})
            list(APPEND ARG_SOURCES "${value}")
        endif()
    endforeach()
    if(ARG_SETUP)
        include("${dir}/${ARG_SETUP}")
    endif()
    foreach(phase INIT START STOP FREE UPDATE MAINTAIN)
        if(ARG_${phase})
            list(APPEND LND_MODULE_HOOKS_${phase} "${ARG_PRIORITY}:${ARG_${phase}}")
            set(LND_MODULE_HOOKS_${phase} ${LND_MODULE_HOOKS_${phase}} PARENT_SCOPE)
        endif()
    endforeach()
    if(NOT ARG_SOURCES)
        if(ARG_DECODER)
            list(APPEND ARG_SOURCES decoder.c)
        endif()
        if(ARG_ENCODER)
            list(APPEND ARG_SOURCES encoder.c)
        endif()
    endif()
    foreach(source ${ARG_SOURCES})
        if((source STREQUAL "decoder.c" AND NOT ARG_DECODER) OR (source STREQUAL "encoder.c" AND NOT ARG_ENCODER))
            continue()
        endif()
        if(source MATCHES "[/\\]" OR NOT EXISTS "${dir}/${source}")
            message(FATAL_ERROR "Module ${NAME} must own its source: ${source}")
        endif()
        list(APPEND LND_MODULE_SOURCES "${dir}/${source}")
    endforeach()
    if(ARG_HEADER)
        list(APPEND LND_MODULE_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/include/${ARG_HEADER}")
    endif()
    list(APPEND LND_MODULE_NAMES ${NAME})
    list(APPEND LND_MODULE_LIBS ${ARG_LIBS})
    list(APPEND LND_MODULE_DEFINES ${ARG_DEFINES})
    foreach(kind DECODER ENCODER)
        if(ARG_${kind})
            list(APPEND LND_${kind}_ORDER "${ARG_PRIORITY}:${NAME}")
            list(APPEND LND_${kind}_NAMES ${NAME})
            set(LND_${kind}_ORDER ${LND_${kind}_ORDER} PARENT_SCOPE)
            set(LND_${kind}_NAMES ${LND_${kind}_NAMES} PARENT_SCOPE)
        endif()
    endforeach()
    foreach(list MODULE_NAMES MODULE_SOURCES MODULE_HEADERS MODULE_LIBS MODULE_DEFINES)
        set(LND_${list} ${LND_${list}} PARENT_SCOPE)
    endforeach()
endfunction()

function(lnd_check_modules)
    foreach(pair ${LND_MODULE_REQUIREMENTS})
        string(REPLACE ":" ";" parts ${pair})
        list(GET parts 0 name)
        list(GET parts 1 req)
        if(NOT name IN_LIST LND_MODULE_NAMES)
            continue()
        endif()
        if(req STREQUAL "OS_MODE" OR req STREQUAL "THREADS")
            if(NOT LND_${req})
                message(FATAL_ERROR "Module ${name} requires LND_${req}=ON")
            endif()
        elseif(NOT req IN_LIST LND_MODULE_NAMES)
            message(FATAL_ERROR "Module ${name} requires module ${req}")
        endif()
    endforeach()
endfunction()

function(lnd_generate_modules OUT_DIR)
    lnd_check_modules()
    foreach(kind DECODER ENCODER)
        list(SORT LND_${kind}_ORDER)
        set(LND_${kind}_NAMES "")
        foreach(entry ${LND_${kind}_ORDER})
            string(REGEX REPLACE "^[^:]+:" "" name ${entry})
            list(APPEND LND_${kind}_NAMES ${name})
        endforeach()
    endforeach()

    set(header "#pragma once\n\n")
    foreach(name ${LND_MODULE_KNOWN})
        string(TOUPPER ${name} upper)
        if(name IN_LIST LND_MODULE_NAMES)
            string(APPEND header "#define LND_MODULE_${upper} 1\n")
        else()
            string(APPEND header "#define LND_MODULE_${upper} 0\n")
        endif()
    endforeach()
    foreach(name ${LND_DECODER_KNOWN})
        string(TOUPPER ${name} upper)
        if(name IN_LIST LND_DECODER_NAMES)
            string(APPEND header "#define LND_MODULE_${upper}_DECODER 1\n")
        else()
            string(APPEND header "#define LND_MODULE_${upper}_DECODER 0\n")
        endif()
    endforeach()
    foreach(name ${LND_ENCODER_KNOWN})
        string(TOUPPER ${name} upper)
        if(name IN_LIST LND_ENCODER_NAMES)
            string(APPEND header "#define LND_MODULE_${upper}_ENCODER 1\n")
        else()
            string(APPEND header "#define LND_MODULE_${upper}_ENCODER 0\n")
        endif()
    endforeach()
    string(APPEND header "#define LND_MODULE_METADATA_OPUS LND_MODULE_METADATA_COMMENTS\n")
    list(LENGTH LND_MODULE_NAMES mcount)
    list(JOIN LND_MODULE_NAMES "," mlist)
    list(LENGTH LND_DECODER_NAMES dcount)
    list(JOIN LND_DECODER_NAMES "," dlist)
    list(LENGTH LND_ENCODER_NAMES ecount)
    list(JOIN LND_ENCODER_NAMES "," elist)
    string(APPEND header "#define LND_MODULES_COUNT ${mcount}\n")
    string(APPEND header "#define LND_MODULES_LIST \"${mlist}\"\n")
    string(APPEND header "#define LND_CODECS_COUNT ${dcount}\n")
    string(APPEND header "#define LND_CODECS_LIST \"${dlist}\"\n")
    string(APPEND header "#define LND_ENCODERS_COUNT ${ecount}\n")
    string(APPEND header "#define LND_ENCODERS_LIST \"${elist}\"\n")
    set(table "#include \"lindar_codecs.h\"\n\n")
    foreach(name ${LND_DECODER_NAMES})
        string(APPEND table "extern const LND_CODEC lnd_codec_${name};\n")
    endforeach()
    string(APPEND table "\nconst LND_CODEC *const lnd_builtin_codecs[] = {\n")
    foreach(name ${LND_DECODER_NAMES})
        string(APPEND table "    &lnd_codec_${name},\n")
    endforeach()
    string(APPEND table "    nullptr,\n};\n\nconst uint32_t lnd_builtin_codecs_count = ${dcount};\n")
    set(etable "#include \"lindar_output.h\"\n\n")
    foreach(name ${LND_ENCODER_NAMES})
        string(APPEND etable "extern const LND_ENCODER lnd_encoder_${name};\n")
    endforeach()
    string(APPEND etable "\nconst LND_ENCODER *const lnd_builtin_encoders[] = {\n")
    foreach(name ${LND_ENCODER_NAMES})
        string(APPEND etable "    &lnd_encoder_${name},\n")
    endforeach()
    string(APPEND etable "    nullptr,\n};\n\nconst uint32_t lnd_builtin_encoders_count = ${ecount};\n")
    set(hooks "#include \"src/module.h\"\n\n")
    foreach(phase INIT START STOP FREE UPDATE MAINTAIN)
        set(entries ${LND_MODULE_HOOKS_${phase}})
        list(SORT entries)
        if(phase STREQUAL "FREE" OR phase STREQUAL "STOP")
            list(REVERSE entries)
        endif()
        set(ret void)
        set(args void)
        set(call "")
        set(prefix "")
        set(suffix "")
        if(phase STREQUAL "INIT" OR phase STREQUAL "START")
            set(ret int32_t)
            set(prefix "    int32_t result = LND_OK;\n")
            set(suffix "    return result;\n")
        endif()
        foreach(entry ${entries})
            string(REGEX REPLACE "^[^:]+:" "" fn ${entry})
            string(APPEND hooks "${ret} ${fn}(${args});\n")
        endforeach()
        string(TOLOWER ${phase} lower)
        string(APPEND hooks "${ret} lnd_modules_${lower}(${args}) {\n${prefix}")
        foreach(entry ${entries})
            string(REGEX REPLACE "^[^:]+:" "" fn ${entry})
            if(ret STREQUAL "int32_t")
                string(APPEND hooks "    result = ${fn}(${call});\n    if (result != LND_OK) return result;\n")
            elseif(ret STREQUAL "uint64_t")
                string(APPEND hooks "    value = ${fn}(${call});\n")
            else()
                string(APPEND hooks "    ${fn}(${call});\n")
            endif()
        endforeach()
        string(APPEND hooks "${suffix}}\n\n")
    endforeach()
    file(MAKE_DIRECTORY ${OUT_DIR})
    lnd_generate_config(${OUT_DIR})
    lnd_generate_provider_table(${OUT_DIR} device_backend "const lnd_backend_vt" lnd_backends lnd_device_backends)
    lnd_generate_provider_table(${OUT_DIR} stretch_backend "const lnd_stretch_backend" lnd_stretch_backends lnd_stretch_backends)
    lnd_generate_provider_table(${OUT_DIR} http_transport "const LND_HTTP_TRANSPORT" lnd_http_transports lnd_http_transports)
    lnd_generate_provider_table(${OUT_DIR} metadata_format "const lnd_metadata_format" lnd_metadata_formats lnd_metadata_formats)
    lnd_generate_errors(${OUT_DIR})
    file(WRITE ${OUT_DIR}/lnd_module_hooks.c.tmp "${hooks}")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${OUT_DIR}/lnd_module_hooks.c.tmp ${OUT_DIR}/lnd_module_hooks.c)
    file(REMOVE ${OUT_DIR}/lnd_module_hooks.c.tmp)

    file(WRITE ${OUT_DIR}/lnd_modules.h.tmp "${header}")
    file(WRITE ${OUT_DIR}/lnd_codecs_table.c.tmp "${table}")
    file(WRITE ${OUT_DIR}/lnd_encoders_table.c.tmp "${etable}")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${OUT_DIR}/lnd_modules.h.tmp ${OUT_DIR}/lnd_modules.h)
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${OUT_DIR}/lnd_codecs_table.c.tmp ${OUT_DIR}/lnd_codecs_table.c)
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${OUT_DIR}/lnd_encoders_table.c.tmp ${OUT_DIR}/lnd_encoders_table.c)
    file(REMOVE ${OUT_DIR}/lnd_modules.h.tmp ${OUT_DIR}/lnd_codecs_table.c.tmp ${OUT_DIR}/lnd_encoders_table.c.tmp ${OUT_DIR}/lnd_codecs.h)
endfunction()

function(lnd_validate_module_layout ROOT)
    get_property(directories GLOBAL PROPERTY LND_MODULE_DIRECTORIES)
    foreach(name ${LND_MODULE_KNOWN})
        get_property(dir GLOBAL PROPERTY LND_DECL_${name}_DIR)
        get_filename_component(directory_name "${dir}" NAME)
        if(NOT directory_name STREQUAL name)
            message(FATAL_ERROR "Module directory must match its name ${name}: ${dir}")
        endif()
        foreach(field SOURCES DECODER_SOURCES ENCODER_SOURCES SOURCES_IF CONFIG ERRORS)
            get_property(sources GLOBAL PROPERTY LND_DECL_${name}_${field})
            foreach(source ${sources})
                string(REGEX REPLACE "^[^:]+:" "" source "${source}")
                if(source MATCHES "[/\\]" OR NOT EXISTS "${dir}/${source}")
                    message(FATAL_ERROR "Module ${name} must own its source: ${source}")
                endif()
            endforeach()
        endforeach()
    endforeach()
    file(GLOB_RECURSE entries LIST_DIRECTORIES true CONFIGURE_DEPENDS "${ROOT}/*")
    list(APPEND entries "${ROOT}")
    foreach(entry ${entries})
        if(IS_DIRECTORY "${entry}" AND NOT entry IN_LIST directories)
            file(GLOB children LIST_DIRECTORIES true "${entry}/*")
            if(NOT children)
                message(FATAL_ERROR "Module category must not be empty: ${entry}")
            endif()
            foreach(child ${children})
                if(NOT IS_DIRECTORY "${child}")
                    message(FATAL_ERROR "Module category may only contain directories: ${child}")
                endif()
            endforeach()
        endif()
    endforeach()
endfunction()
