lnd_import_option(LND_MODULE_METADATA_OPUS LND_MODULE_METADATA_COMMENTS)

foreach(backend NULL WASAPI ALSA AAUDIO COREAUDIO)
    lnd_import_option(LND_ENABLE_${backend} LND_MODULE_${backend})
endforeach()
foreach(container HLS MP4)
    lnd_import_option(LND_HTTP_${container} LND_MODULE_HTTP_${container})
endforeach()

set(LND_HTTP_TRANSPORT CURL CACHE STRING "HTTP transport: CURL or CUSTOM")
set_property(CACHE LND_HTTP_TRANSPORT PROPERTY STRINGS CURL CUSTOM)
string(TOUPPER "${LND_HTTP_TRANSPORT}" LND_HTTP_TRANSPORT)
option(LND_HTTP_ICY "Enable ICY metadata" ON)
option(LND_HTTP_LL_HLS "Enable Low-Latency HLS" ON)
option(LND_HTTP_AES128 "Enable AES-128 HLS segments" ${LND_OS_MODE})

set(LND_PLATFORM_WINDOWS ${WIN32})
set(LND_PLATFORM_APPLE ${APPLE})
set(LND_PLATFORM_ANDROID ${ANDROID})
set(LND_PLATFORM_IOS OFF)
if(APPLE AND CMAKE_SYSTEM_NAME STREQUAL "iOS")
    set(LND_PLATFORM_IOS ON)
endif()
set(LND_PLATFORM_LINUX OFF)
if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT ANDROID)
    set(LND_PLATFORM_LINUX ON)
endif()
set(LND_ANDROID_API ${CMAKE_SYSTEM_VERSION})
if(DEFINED ANDROID_PLATFORM_LEVEL)
    set(LND_ANDROID_API ${ANDROID_PLATFORM_LEVEL})
endif()
set(LND_GSTREAMER_AVAILABLE OFF)
if(LND_PLATFORM_LINUX AND LND_OS_MODE AND LND_THREADS)
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
        pkg_check_modules(LND_GSTREAMER QUIET gstreamer-app-1.0>=1.14 gstreamer-audio-1.0>=1.14)
        set(LND_GSTREAMER_AVAILABLE ${LND_GSTREAMER_FOUND})
    endif()
endif()
