set(LND_PACKAGE custom CACHE STRING "Fixed module package or custom selection")
set(LND_PACKAGES custom linda lindar_pitya lindar lindar_quanta)
set_property(CACHE LND_PACKAGE PROPERTY STRINGS ${LND_PACKAGES})
if(NOT LND_PACKAGE IN_LIST LND_PACKAGES)
    message(FATAL_ERROR "Unknown LND_PACKAGE '${LND_PACKAGE}'; choose ${LND_PACKAGES}")
endif()

set(LND_LIBRARY_TARGET lindar)
if(NOT LND_PACKAGE STREQUAL "custom")
    set(LND_LIBRARY_TARGET ${LND_PACKAGE})
    if(LND_PACKAGE STREQUAL "linda" OR LND_PACKAGE STREQUAL "lindar_pitya")
        set(LND_MINIMAL ON CACHE BOOL "Disable optional modules by default" FORCE)
    else()
        set(LND_MINIMAL OFF CACHE BOOL "Disable optional modules by default" FORCE)
    endif()
    set(package_os ON)
    if(LND_PACKAGE STREQUAL "linda")
        set(package_os OFF)
    endif()
    set(LND_OS_MODE ${package_os} CACHE BOOL "Enable operating system integration" FORCE)
    set(LND_THREADS ${package_os} CACHE BOOL "Enable thread support" FORCE)
    set(LND_USE_LIBC_ALLOC ${package_os} CACHE BOOL "Use libc allocation when custom callbacks are not configured" FORCE)
    set(LND_BUILD_DECODERS ON CACHE BOOL "Enable format decoders" FORCE)
    set(LND_BUILD_ENCODERS ON CACHE BOOL "Enable format encoders" FORCE)
    if(LND_PACKAGE STREQUAL "lindar" OR LND_PACKAGE STREQUAL "lindar_quanta")
        set(LND_HTTP_TRANSPORT CURL CACHE STRING "HTTP transport: CURL or CUSTOM" FORCE)
        set(LND_HTTP_ICY ON CACHE BOOL "Enable ICY metadata" FORCE)
        set(LND_HTTP_LL_HLS ON CACHE BOOL "Enable Low-Latency HLS" FORCE)
        set(LND_HTTP_AES128 ON CACHE BOOL "Enable AES-128 HLS segments" FORCE)
    endif()
    unset(package_os)
endif()

function(lnd_apply_package)
    if(LND_PACKAGE STREQUAL "custom")
        return()
    endif()
    set(selected "")
    if(LND_PACKAGE STREQUAL "lindar_pitya")
        set(selected
            aaudio android ios adpcm alsa buffers codecs coreaudio devices file_io files graph io null output pcm_float
            queue sink stream wasapi wav)
    elseif(NOT LND_PACKAGE STREQUAL "linda")
        set(selected
            aac aaudio android ios adpcm aiff alsa analysis audiotoolbox autofree buffers codecs coreaudio devices dsp
            file_io files flac graph gstreamer io log mediacodec mediafoundation metadata metadata_comments
            metadata_id3v1 metadata_id3v2 metadata_io metadata_wave mp3 notify null ogg opus output pcm_float
            queue simd sink slide speex stream vorbis wasapi wav
            cast decode demux http http_curl http_file http_hls http_mp4 monitor sinc_asm soundtouch stretch)
    endif()
    if(LND_PACKAGE STREQUAL "lindar_quanta")
        list(APPEND selected asio bungee effects ffmpeg ffmpeg_stream midi vst3)
    endif()
    foreach(name ${selected})
        if(NOT name IN_LIST LND_MODULE_KNOWN)
            message(FATAL_ERROR "Package ${LND_PACKAGE} refers to unknown module ${name}")
        endif()
    endforeach()
    foreach(name ${LND_MODULE_KNOWN})
        string(TOUPPER ${name} upper)
        get_property(internal GLOBAL PROPERTY LND_DECL_${name}_INTERNAL)
        set(mode OFF)
        if(internal)
            set(mode AUTO)
        elseif(name IN_LIST selected)
            set(mode ON)
            get_property(platform GLOBAL PROPERTY LND_DECL_${name}_PLATFORM)
            get_property(api GLOBAL PROPERTY LND_DECL_${name}_MIN_API)
            if((platform AND NOT LND_PLATFORM_${platform}) OR (api AND LND_ANDROID_API LESS api))
                set(mode OFF)
            endif()
        endif()
        set_property(GLOBAL PROPERTY LND_DECL_${name}_REQUEST ${mode})
        if(NOT internal)
            set(LND_MODULE_${upper} ${mode} CACHE STRING "Module selection: AUTO, ON or OFF" FORCE)
        endif()
        foreach(kind DECODER ENCODER)
            get_property(present GLOBAL PROPERTY LND_DECL_${name}_${kind})
            if(present)
                set(LND_MODULE_${upper}_${kind} AUTO CACHE STRING "Module selection: AUTO, ON or OFF" FORCE)
                set_property(GLOBAL PROPERTY LND_DECL_${name}_${kind}_REQUEST AUTO)
            endif()
        endforeach()
    endforeach()
endfunction()
