function(lnd_write_generated PATH CONTENT)
    file(WRITE "${PATH}.tmp" "${CONTENT}")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${PATH}.tmp" "${PATH}")
    file(REMOVE "${PATH}.tmp")
endfunction()

function(lnd_generate_config OUT_DIR)
    set(definitions "${CMAKE_CURRENT_SOURCE_DIR}/src/config.def")
    set(header "#pragma once\n\n")
    foreach(name ${LND_MODULE_NAMES})
        get_property(config GLOBAL PROPERTY LND_DECL_${name}_CONFIG)
        if(config)
            get_property(dir GLOBAL PROPERTY LND_DECL_${name}_DIR)
            list(APPEND definitions "${dir}/${config}")
            string(APPEND header "#include \"${dir}/config.h\"\n")
        endif()
    endforeach()
    set(handlers "#pragma once\n\n")
    set(public "")
    set(private "")
    set(labels "")
    foreach(definition ${definitions})
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${definition}")
        file(STRINGS "${definition}" rows REGEX "^LND_CONFIG\\(")
        foreach(row ${rows})
            if(row MATCHES "^LND_CONFIG\\([^,]+, *\"([^\"]+)\"")
                set(label "${CMAKE_MATCH_1}")
                if(label IN_LIST labels)
                    message(FATAL_ERROR "Duplicate configuration name ${label}")
                endif()
                list(APPEND labels "${label}")
                list(APPEND public "${row}")
            else()
                list(APPEND private "${row}")
            endif()
        endforeach()
    endforeach()
    set(keys "")
    set(entries "")
    foreach(row ${public} ${private})
        string(REGEX REPLACE "^LND_CONFIG\\(([A-Z0-9_]+),.*" "\\1" key "${row}")
        if(key IN_LIST keys)
            message(FATAL_ERROR "Duplicate configuration key ${key}")
        endif()
        list(LENGTH keys index)
        string(APPEND header "#define LND_CONFIG_INDEX_${key} ${index}\n")
        string(APPEND entries "${row}\n")
        list(APPEND keys ${key})
    endforeach()
    list(LENGTH keys count)
    list(LENGTH public public_count)
    string(APPEND header "#define LND_CONFIG_KEY_COUNT ${count}\n#define LND_CONFIG_PUBLIC_KEY_COUNT ${public_count}\n\n#ifndef LND_CONFIG_DEFINITIONS\n")
    foreach(key ${keys})
        string(APPEND header "#define ${key} (&lnd_config_keys[LND_CONFIG_INDEX_${key}])\n")
    endforeach()
    string(APPEND header "#endif\n")
    set(includes "#include \"lnd_config_entries.h\"\n")
    lnd_write_generated("${OUT_DIR}/lnd_config_entries.h" "${entries}")
    set(table "#define LND_CONFIG_DEFINITIONS\n#include \"src/config.h\"\n\n")
    string(APPEND table "#define LND_CONFIG(key, label, kind, stage, lo, hi, initial) {initial, &(const lnd_cfg_desc){label, kind, stage, lo, hi, initial}},\n")
    string(APPEND table "LND_CONFIG_KEY lnd_config_keys[] = {\n${includes}};\n#undef LND_CONFIG\n\n")
    string(APPEND table "#define LND_CONFIG(key, label, kind, stage, lo, hi, initial) LND_CONFIG_KEY *const key = &lnd_config_keys[LND_CONFIG_INDEX_##key];\n${includes}#undef LND_CONFIG\n")
    lnd_write_generated("${OUT_DIR}/lnd_config_keys.h" "${header}")
    lnd_write_generated("${OUT_DIR}/lnd_config_table.c" "${table}")
    set(cases "")
    foreach(name ${LND_MODULE_NAMES})
        get_property(handler GLOBAL PROPERTY LND_DECL_${name}_CONFIG_SET)
        if(handler)
            get_property(config GLOBAL PROPERTY LND_DECL_${name}_CONFIG)
            get_property(dir GLOBAL PROPERTY LND_DECL_${name}_DIR)
            if(NOT config)
                message(FATAL_ERROR "Configuration handler ${name} must own CONFIG")
            endif()
            file(STRINGS "${dir}/${config}" rows REGEX "^LND_CONFIG\\(")
            string(APPEND handlers "int32_t ${handler}(LND_CONFIG_KEY *key, uint64_t value);\n")
            foreach(row ${rows})
                string(REGEX REPLACE "^LND_CONFIG\\(([A-Z0-9_]+),.*" "\\1" key "${row}")
                string(APPEND cases "    case LND_CONFIG_INDEX_${key}:\n")
            endforeach()
            string(APPEND cases "        return ${handler}(key, value);\n")
        endif()
    endforeach()
    string(APPEND handlers "\nLND_INLINE int32_t lnd_config_notify_set(LND_CONFIG_KEY *key, uint64_t value) {\n")
    if(cases)
        string(APPEND handlers "    switch (key - lnd_config_keys) {\n${cases}    default: return LND_OK;\n    }\n")
    else()
        string(APPEND handlers "    LND_UNUSED(key);\n    LND_UNUSED(value);\n    return LND_OK;\n")
    endif()
    string(APPEND handlers "}\n\n")
    lnd_write_generated("${OUT_DIR}/lnd_config_handlers.h" "${handlers}")
endfunction()

function(lnd_generate_provider_table OUT_DIR KIND TYPE TABLE FILE)
    lnd_module_providers(${KIND} providers)
    set(header "#pragma once\n\n")
    set(entries "")
    set(symbols "")
    foreach(name ${providers})
        if(name IN_LIST LND_MODULE_NAMES)
            get_property(implementations GLOBAL PROPERTY LND_DECL_${name}_PROVIDER)
            if(NOT implementations)
                message(FATAL_ERROR "Provider ${name} must declare PROVIDER")
            endif()
            foreach(symbol ${implementations})
                if(symbol IN_LIST symbols)
                    message(FATAL_ERROR "Duplicate provider ${symbol}")
                endif()
                list(APPEND symbols ${symbol})
                string(APPEND header "extern ${TYPE} ${symbol};\n")
                string(APPEND entries "    &${symbol},\n")
            endforeach()
        endif()
    endforeach()
    string(APPEND header "\nstatic ${TYPE} *const ${TABLE}[] = {\n${entries}    nullptr,\n};\n")
    if(KIND STREQUAL "http_transport")
        set(default nullptr)
        if(NOT LND_HTTP_TRANSPORT STREQUAL "CUSTOM" AND http IN_LIST LND_MODULE_NAMES)
            string(TOLOWER "${LND_HTTP_TRANSPORT}" transport)
            get_property(symbol GLOBAL PROPERTY LND_DECL_http_${transport}_PROVIDER)
            set(default "&${symbol}")
        endif()
        string(APPEND header "\n#define LND_HTTP_DEFAULT_TRANSPORT ${default}\n")
    endif()
    lnd_write_generated("${OUT_DIR}/${FILE}.h" "${header}")
endfunction()

function(lnd_generate_errors OUT_DIR)
    set(source "#include \"src/module.h\"\n")
    set(cases "")
    foreach(name ${LND_MODULE_NAMES})
        get_property(errors GLOBAL PROPERTY LND_DECL_${name}_ERRORS)
        if(errors)
            get_property(dir GLOBAL PROPERTY LND_DECL_${name}_DIR)
            get_property(header GLOBAL PROPERTY LND_DECL_${name}_HEADER)
            string(APPEND source "#include \"${header}\"\n")
            string(APPEND cases "#include \"${dir}/${errors}\"\n")
        endif()
    endforeach()
    string(APPEND source "\nconst char *lnd_modules_error_string(int32_t code) {\n    switch (code) {\n#define LND_ERROR(code, text) case code: return text;\n${cases}#undef LND_ERROR\n    default: return \"unknown\";\n    }\n}\n")
    lnd_write_generated("${OUT_DIR}/lnd_module_errors.c" "${source}")
endfunction()
