set(LND_VENDOR_DIR ${CMAKE_CURRENT_SOURCE_DIR}/vendor)
include(${CMAKE_CURRENT_LIST_DIR}/vendor/openssl.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/vendor/curl.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/vendor/bungee.cmake)

function(lnd_vendor_quiet TARGET)
    if(CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
        target_compile_options(${TARGET} PRIVATE -w)
    endif()
endfunction()

function(lnd_vendor_soundtouch)
    if(TARGET lnd_soundtouch)
        return()
    endif()
    set(dir ${LND_VENDOR_DIR}/soundtouch)
    set(sources AAFilter.cpp cpu_detect_x86.cpp FIFOSampleBuffer.cpp FIRFilter.cpp InterpolateCubic.cpp
        InterpolateLinear.cpp InterpolateShannon.cpp RateTransposer.cpp SoundTouch.cpp sse_optimized.cpp TDStretch.cpp)
    include(${CMAKE_CURRENT_SOURCE_DIR}/modules/processing/stretch/soundtouch/vendor_safety.cmake)
    add_library(lnd_soundtouch STATIC ${patched_sources})
    target_include_directories(lnd_soundtouch PRIVATE ${dir}/include ${dir}/source/SoundTouch)
    target_compile_definitions(lnd_soundtouch PRIVATE SOUNDTOUCH_FLOAT_SAMPLES=1)
    set_target_properties(lnd_soundtouch PROPERTIES CXX_STANDARD 17 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF POSITION_INDEPENDENT_CODE ON CXX_VISIBILITY_PRESET hidden)
    if(MSVC)
        target_compile_options(lnd_soundtouch PRIVATE /EHsc /O2)
    else()
        target_compile_options(lnd_soundtouch PRIVATE -fexceptions -ffunction-sections -fdata-sections
            $<$<CONFIG:Release>:-O3> -fno-math-errno -fno-trapping-math)
    endif()
    option(LND_SOUNDTOUCH_SIMD "Enable vendor SoundTouch SIMD kernels" ON)
    if(LND_SOUNDTOUCH_SIMD)
        include(CheckCXXSourceCompiles)
        check_cxx_source_compiles("#if !defined(__aarch64__) && !defined(_M_ARM64) && !defined(__ARM_NEON)\n#error no_neon\n#endif\nint main() { return 0; }" LND_SOUNDTOUCH_NEON)
        if(LND_SOUNDTOUCH_NEON)
            target_compile_definitions(lnd_soundtouch PRIVATE SOUNDTOUCH_USE_NEON=1)
        endif()
    else()
        target_compile_definitions(lnd_soundtouch PRIVATE SOUNDTOUCH_DISABLE_X86_OPTIMIZATIONS=1)
    endif()
    lnd_vendor_quiet(lnd_soundtouch)
endfunction()

function(lnd_vendor_ogg)
    if(TARGET lnd_ogg)
        return()
    endif()
    set(dir ${LND_VENDOR_DIR}/ogg)
    set(gen ${LND_GENERATED_DIR}/ogg/ogg)
    file(MAKE_DIRECTORY ${gen})
    file(WRITE ${gen}/config_types.h.tmp "#pragma once\n#include <stdint.h>\ntypedef int16_t ogg_int16_t;\ntypedef uint16_t ogg_uint16_t;\ntypedef int32_t ogg_int32_t;\ntypedef uint32_t ogg_uint32_t;\ntypedef int64_t ogg_int64_t;\ntypedef uint64_t ogg_uint64_t;\n")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${gen}/config_types.h.tmp ${gen}/config_types.h)
    file(REMOVE ${gen}/config_types.h.tmp)
    add_library(lnd_ogg STATIC ${dir}/src/framing.c ${dir}/src/bitwise.c)
    target_include_directories(lnd_ogg PUBLIC ${dir}/include ${LND_GENERATED_DIR}/ogg)
    lnd_vendor_quiet(lnd_ogg)
endfunction()

function(lnd_vendor_vorbis)
    lnd_vendor_ogg()
    if(TARGET lnd_vorbisfile)
        return()
    endif()
    set(dir ${LND_VENDOR_DIR}/vorbis)
    set(sources mdct.c smallft.c block.c envelope.c window.c lsp.c lpc.c analysis.c synthesis.c psy.c info.c floor1.c floor0.c res0.c mapping0.c registry.c codebook.c sharedbook.c lookup.c bitrate.c)
    list(TRANSFORM sources PREPEND ${dir}/lib/)
    add_library(lnd_vorbis STATIC ${sources})
    target_include_directories(lnd_vorbis PUBLIC ${dir}/include PRIVATE ${dir}/lib)
    target_link_libraries(lnd_vorbis PUBLIC lnd_ogg)
    add_library(lnd_vorbisfile STATIC ${dir}/lib/vorbisfile.c)
    target_include_directories(lnd_vorbisfile PUBLIC ${dir}/include PRIVATE ${dir}/lib)
    target_link_libraries(lnd_vorbisfile PUBLIC lnd_vorbis)
    add_library(lnd_vorbisenc STATIC ${dir}/lib/vorbisenc.c)
    target_include_directories(lnd_vorbisenc PUBLIC ${dir}/include PRIVATE ${dir}/lib)
    target_link_libraries(lnd_vorbisenc PUBLIC lnd_vorbis)
    include(CheckIncludeFile)
    check_include_file(alloca.h LND_HAVE_ALLOCA_H)
    if(LND_HAVE_ALLOCA_H)
        foreach(target lnd_vorbis lnd_vorbisfile lnd_vorbisenc)
            target_compile_definitions(${target} PRIVATE HAVE_ALLOCA_H=1)
        endforeach()
    endif()
    lnd_vendor_quiet(lnd_vorbisenc)
    lnd_vendor_quiet(lnd_vorbis)
    lnd_vendor_quiet(lnd_vorbisfile)
endfunction()

function(lnd_vendor_opus)
    if(TARGET opus)
        return()
    endif()
    if(LND_MINIMAL)
        option(OPUS_FIXED_POINT "Use integer Opus kernels" ON)
        if(LND_MODULE_OPUS_ENCODER)
            set(LND_OPUS_FLOAT_DEFAULT ON)
        else()
            set(LND_OPUS_FLOAT_DEFAULT OFF)
        endif()
        option(OPUS_ENABLE_FLOAT_API "Enable Opus float API" ${LND_OPUS_FLOAT_DEFAULT})
        if(LND_MODULE_OPUS_ENCODER AND NOT OPUS_ENABLE_FLOAT_API)
            message(FATAL_ERROR "The Opus encoder requires OPUS_ENABLE_FLOAT_API=ON; disable LND_MODULE_OPUS_ENCODER for integer decoding")
        endif()
        option(OPUS_DISABLE_INTRINSICS "Disable Opus platform intrinsics" ON)
        if(NOT LND_OS_MODE)
            option(OPUS_STACK_PROTECTOR "Require a target stack protector runtime" OFF)
            option(OPUS_HARDENING "Enable Opus assertions and diagnostic runtime" OFF)
            option(OPUS_FORTIFY_SOURCE "Require fortified libc functions" OFF)
        endif()
    endif()
    set(OPUS_BUILD_SHARED_LIBRARY OFF CACHE BOOL "" FORCE)
    set(OPUS_BUILD_TESTING OFF CACHE BOOL "" FORCE)
    set(OPUS_BUILD_PROGRAMS OFF CACHE BOOL "" FORCE)
    set(OPUS_INSTALL_PKG_CONFIG_MODULE OFF CACHE BOOL "" FORCE)
    set(OPUS_INSTALL_CMAKE_CONFIG_MODULE OFF CACHE BOOL "" FORCE)
    add_subdirectory(${LND_VENDOR_DIR}/opus ${CMAKE_BINARY_DIR}/vendor/opus EXCLUDE_FROM_ALL)
    lnd_vendor_quiet(opus)
    if(LND_MINIMAL AND CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
        target_compile_options(opus PRIVATE -ffunction-sections -fdata-sections)
    endif()
endfunction()

function(lnd_vendor_opusfile)
    lnd_vendor_ogg()
    lnd_vendor_opus()
    if(TARGET lnd_opusfile)
        return()
    endif()
    set(dir ${LND_VENDOR_DIR}/opusfile)
    set(source ${dir}/src/opusfile.c)
    if(NOT LND_OS_MODE)
        include(${CMAKE_CURRENT_SOURCE_DIR}/modules/formats/opus/vendor.cmake)
    endif()
    add_library(lnd_opusfile STATIC ${source} ${dir}/src/info.c ${dir}/src/internal.c)
    if(LND_OS_MODE)
        target_sources(lnd_opusfile PRIVATE ${dir}/src/stream.c)
    else()
        target_compile_definitions(lnd_opusfile PRIVATE OP_DISABLE_STREAMS)
    endif()
    if(OPUS_FIXED_POINT)
        target_compile_definitions(lnd_opusfile PRIVATE OP_FIXED_POINT)
    endif()
    if(NOT OPUS_ENABLE_FLOAT_API)
        target_compile_definitions(lnd_opusfile PRIVATE OP_DISABLE_FLOAT_API)
    endif()
    if(LND_MINIMAL AND CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
        target_compile_options(lnd_opusfile PRIVATE -ffunction-sections -fdata-sections)
        target_compile_options(lnd_ogg PRIVATE -ffunction-sections -fdata-sections)
    endif()
    target_include_directories(lnd_opusfile PUBLIC ${dir}/include PRIVATE ${dir}/src)
    target_compile_definitions(lnd_opusfile PRIVATE OP_DISABLE_HTTP)
    target_link_libraries(lnd_opusfile PUBLIC opus lnd_ogg)
    lnd_vendor_quiet(lnd_opusfile)
endfunction()

function(lnd_vendor_flac)
    if(TARGET FLAC)
        return()
    endif()
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
    set(BUILD_CXXLIBS OFF CACHE BOOL "" FORCE)
    set(BUILD_PROGRAMS OFF CACHE BOOL "" FORCE)
    set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
    set(BUILD_DOCS OFF CACHE BOOL "" FORCE)
    set(BUILD_UTILS OFF CACHE BOOL "" FORCE)
    set(INSTALL_MANPAGES OFF CACHE BOOL "" FORCE)
    set(INSTALL_PKGCONFIG_MODULES OFF CACHE BOOL "" FORCE)
    set(INSTALL_CMAKE_CONFIG_MODULE OFF CACHE BOOL "" FORCE)
    set(WITH_OGG OFF CACHE BOOL "" FORCE)
    set(WITH_FORTIFY_SOURCE OFF CACHE BOOL "" FORCE)
    set(WITH_STACK_PROTECTOR OFF CACHE BOOL "" FORCE)
    set(ENABLE_MULTITHREADING OFF CACHE BOOL "" FORCE)
    if(ANDROID AND DEFINED ANDROID_PLATFORM_LEVEL)
        set(CMAKE_SYSTEM_VERSION ${ANDROID_PLATFORM_LEVEL})
        unset(HAVE_FSEEKO CACHE)
    endif()
    add_subdirectory(${LND_VENDOR_DIR}/flac ${CMAKE_BINARY_DIR}/vendor/flac EXCLUDE_FROM_ALL)
    lnd_vendor_quiet(FLAC)
endfunction()

function(lnd_vendor_fdk_aac)
    if(TARGET lnd_fdk)
        return()
    endif()
    set(dir ${LND_VENDOR_DIR}/fdk-aac)
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
    set(BUILD_PROGRAMS OFF CACHE BOOL "" FORCE)
    add_subdirectory(${dir} ${CMAKE_BINARY_DIR}/vendor/fdk-aac EXCLUDE_FROM_ALL)
    lnd_vendor_quiet(fdk-aac)
    if(ANDROID)
        configure_file(${CMAKE_CURRENT_SOURCE_DIR}/modules/formats/aac/android_log.h ${LND_GENERATED_DIR}/aac/log/log.h COPYONLY)
        target_include_directories(fdk-aac PRIVATE ${LND_GENERATED_DIR}/aac)
        target_link_libraries(fdk-aac PUBLIC log)
    endif()
    add_library(lnd_fdk INTERFACE)
    target_include_directories(lnd_fdk INTERFACE ${dir}/libAACdec/include ${dir}/libAACenc/include ${dir}/libSYS/include)
    target_link_libraries(lnd_fdk INTERFACE fdk-aac)
endfunction()

function(lnd_vendor_lame)
    if(TARGET lnd_lame)
        return()
    endif()
    set(dir ${LND_VENDOR_DIR}/lame)
    set(gen ${LND_GENERATED_DIR}/lame)
    file(MAKE_DIRECTORY ${gen})
    include(CheckTypeSize)
    check_type_size(long LND_LAME_LONG)
    set(cfg "#pragma once\n#include <stdint.h>\n#define STDC_HEADERS 1\n#define HAVE_STDINT_H 1\n#define HAVE_INTTYPES_H 1\n#define HAVE_STDLIB_H 1\n#define HAVE_STRING_H 1\n#define HAVE_ERRNO_H 1\n#define HAVE_FCNTL_H 1\n#define HAVE_LIMITS_H 1\n#define HAVE_STRCHR 1\n#define HAVE_MEMCPY 1\n")
    string(APPEND cfg "#define SIZEOF_SHORT 2\n#define SIZEOF_INT 4\n#define SIZEOF_LONG ${LND_LAME_LONG}\n#define SIZEOF_LONG_LONG 8\n#define SIZEOF_FLOAT 4\n#define SIZEOF_DOUBLE 8\n#define SIZEOF_UNSIGNED_SHORT 2\n#define SIZEOF_UNSIGNED_INT 4\n#define SIZEOF_UNSIGNED_LONG ${LND_LAME_LONG}\n#define SIZEOF_UNSIGNED_LONG_LONG 8\n")
    file(STRINGS ${dir}/configure.ac version REGEX "^AC_INIT")
    string(REGEX MATCH "[0-9]+[.][0-9]+([.][0-9]+)?" version "${version}")
    string(APPEND cfg "#define HAVE_IEEE754_FLOAT32_T 1\n#define HAVE_IEEE754_FLOAT64_T 1\ntypedef float ieee754_float32_t;\ntypedef double ieee754_float64_t;\ntypedef long double ieee854_float80_t;\n#define PACKAGE \"lame\"\n#define VERSION \"${version}\"\n#define LAME_LIBRARY_BUILD 1\n#define USE_FAST_LOG 1\n")
    file(WRITE ${gen}/config.h.tmp "${cfg}")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${gen}/config.h.tmp ${gen}/config.h)
    file(REMOVE ${gen}/config.h.tmp)
    set(sources VbrTag.c bitstream.c encoder.c fft.c gain_analysis.c id3tag.c lame.c newmdct.c presets.c psymodel.c quantize.c quantize_pvt.c reservoir.c set_get.c tables.c takehiro.c util.c vbrquantize.c version.c)
    list(TRANSFORM sources PREPEND ${dir}/libmp3lame/)
    add_library(lnd_lame STATIC ${sources})
    target_include_directories(lnd_lame PUBLIC ${dir}/include PRIVATE ${gen} ${dir}/libmp3lame ${dir}/mpglib)
    target_compile_definitions(lnd_lame PRIVATE HAVE_CONFIG_H)
    set_target_properties(lnd_lame PROPERTIES C_STANDARD 11 C_EXTENSIONS ON)
    lnd_vendor_quiet(lnd_lame)
endfunction()

function(lnd_vendor_ffmpeg)
    if(TARGET lnd_ffmpeg)
        return()
    endif()
    include(ExternalProject)
    include(ProcessorCount)
    set(src ${LND_VENDOR_DIR}/ffmpeg)
    set(build ${CMAKE_BINARY_DIR}/vendor/ffmpeg)
    get_filename_component(compiler_dir ${CMAKE_C_COMPILER} DIRECTORY)
    if(WIN32)
        set(msys_bin ${compiler_dir}/../../usr/bin C:/msys64/usr/bin)
        find_program(LND_SH NAMES sh PATHS ${msys_bin} NO_DEFAULT_PATH)
        find_program(LND_MAKE NAMES make PATHS ${msys_bin} NO_DEFAULT_PATH)
    else()
        find_program(LND_SH NAMES sh)
        find_program(LND_MAKE NAMES gmake make)
    endif()
    if(NOT LND_SH OR NOT LND_MAKE)
        message(FATAL_ERROR "LND_MODULE_FFMPEG needs sh and make to run FFmpeg's configure (MSYS2: pacman -S make)")
    endif()
    ProcessorCount(jobs)
    if(jobs EQUAL 0)
        set(jobs 4)
    endif()
    execute_process(COMMAND ${CMAKE_C_COMPILER} -dumpmachine OUTPUT_VARIABLE triple OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE triple_rc)
    if(triple_rc EQUAL 0 AND triple MATCHES "^([A-Za-z0-9_]+)-")
        string(TOLOWER "${CMAKE_MATCH_1}" arch)
    else()
        string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" arch)
    endif()
    if(arch MATCHES "arm64|aarch64")
        set(arch aarch64)
    elseif(arch MATCHES "amd64|x86_64")
        set(arch x86_64)
    elseif(arch MATCHES "^(x86|i[3-6]86)$")
        set(arch x86)
    endif()
    set(flags --arch=${arch} --enable-static --disable-shared --disable-programs --disable-doc --disable-avdevice --disable-avfilter --disable-swscale --disable-network --disable-autodetect --disable-encoders --disable-protocols --disable-devices --disable-filters --disable-hwaccels --disable-bsfs --disable-decoders --disable-debug)
    if(WIN32)
        list(APPEND flags --target-os=mingw64)
    endif()
    find_program(LND_NASM NAMES nasm)
    if(NOT LND_NASM)
        list(APPEND flags --disable-x86asm)
    endif()
    file(STRINGS ${CMAKE_CURRENT_SOURCE_DIR}/modules/formats/ffmpeg/decoders.txt default_decoders)
    set(LND_FFMPEG_DECODERS "${default_decoders}" CACHE STRING "FFmpeg decoders compiled into the ffmpeg module")
    set(LND_FFMPEG_FLAGS "" CACHE STRING "Extra flags for FFmpeg's configure")
    foreach(decoder ${LND_FFMPEG_DECODERS})
        list(APPEND flags --enable-decoder=${decoder})
    endforeach()
    file(STRINGS ${CMAKE_CURRENT_SOURCE_DIR}/modules/formats/ffmpeg/encoders.txt default_encoders)
    set(LND_FFMPEG_ENCODERS "${default_encoders}" CACHE STRING "FFmpeg encoders compiled into the ffmpeg module")
    foreach(encoder ${LND_FFMPEG_ENCODERS})
        list(APPEND flags --enable-encoder=${encoder})
    endforeach()
    list(APPEND flags ${LND_FFMPEG_FLAGS})
    list(JOIN flags " " LND_FF_FLAGS)
    set(LND_FF_SRC ${src})
    set(LND_FF_BUILD ${build})
    set(LND_FF_CC ${CMAKE_C_COMPILER})
    set(LND_FF_MAKE ${LND_MAKE})
    set(LND_FF_JOBS ${jobs})
    configure_file(${CMAKE_CURRENT_SOURCE_DIR}/modules/formats/ffmpeg/build.sh.in ${build}/build.sh @ONLY)
    configure_file(${src}/RELEASE ${build}/source-release COPYONLY)
    set(libs "")
    foreach(lib avformat avcodec swresample avutil)
        list(APPEND libs ${build}/lib${lib}/lib${lib}.a)
    endforeach()
    ExternalProject_Add(lnd_ffmpeg_build
        PREFIX ${build}/ep
        SOURCE_DIR ${src}
        BINARY_DIR ${build}
        CONFIGURE_COMMAND ${LND_SH} ${build}/build.sh configure
        BUILD_COMMAND ${LND_SH} ${build}/build.sh build
        INSTALL_COMMAND ""
        BUILD_BYPRODUCTS ${libs}
        LOG_CONFIGURE ON
        LOG_BUILD ON
        LOG_OUTPUT_ON_FAILURE ON)
    ExternalProject_Add_StepDependencies(lnd_ffmpeg_build configure ${build}/build.sh ${build}/source-release)
    add_library(lnd_ffmpeg INTERFACE)
    add_dependencies(lnd_ffmpeg lnd_ffmpeg_build)
    target_include_directories(lnd_ffmpeg INTERFACE ${src} ${build})
    target_link_libraries(lnd_ffmpeg INTERFACE ${libs})
    if(WIN32)
        target_link_libraries(lnd_ffmpeg INTERFACE bcrypt ole32 user32)
    elseif(UNIX)
        target_link_libraries(lnd_ffmpeg INTERFACE m pthread)
    endif()
endfunction()
