#pragma once

#include "lindar_devices.h"

extern LND_CONFIG_KEY *const LND_CFG_DEVICES_BACKEND;
extern LND_CONFIG_KEY *const LND_CFG_DEVICES_OUTPUT_DEVICE;
extern LND_CONFIG_KEY *const LND_CFG_DEVICES_INPUT_DEVICE;
extern LND_CONFIG_KEY *const LND_CFG_DEVICES_OUTPUT_INSTANCE;
extern LND_CONFIG_KEY *const LND_CFG_DEVICES_DEVICE_PROC;
extern LND_CONFIG_KEY *const LND_CFG_DEVICES_DEVICE_USER;

#ifndef LND_DEFAULT_AUTO_OPEN
#define LND_DEFAULT_AUTO_OPEN 1
#endif

#ifndef LND_DEFAULT_FORMAT
#define LND_DEFAULT_FORMAT LND_FORMAT_NONE
#endif

#ifndef LND_DEFAULT_DEVICE_PERIOD_FRAMES
#define LND_DEFAULT_DEVICE_PERIOD_FRAMES 0
#endif

#ifndef LND_DEFAULT_DEVICE_PERIODS
#define LND_DEFAULT_DEVICE_PERIODS 2
#endif

#ifndef LND_DEFAULT_EXCLUSIVE
#define LND_DEFAULT_EXCLUSIVE 0
#endif

#ifndef LND_DEFAULT_THREAD_PRIORITY
#define LND_DEFAULT_THREAD_PRIORITY LND_DEVICE_THREAD_PRIORITY_REALTIME
#endif

#ifndef LND_DEFAULT_FOLLOW_DEFAULT
#define LND_DEFAULT_FOLLOW_DEFAULT 1
#endif

#ifndef LND_DEFAULT_REOPEN_INTERVAL_MS
#define LND_DEFAULT_REOPEN_INTERVAL_MS 1000
#endif

#ifndef LND_DEFAULT_RUN_MODE
#define LND_DEFAULT_RUN_MODE LND_MODE_REALTIME
#endif
